GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "todo":"humaira"
}

###

PUT http://localhost:3000
Content-Length: application/json
Accept: application/json

{
    "id":3,
    "todo":"namasaya"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "id":2
}
